# Generated by Django 5.2.8 on 2025-11-22 02:42

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def deactivate_duplicate_objectives(apps, schema_editor):
    Objective = apps.get_model('objectives', 'Objective')
    duplicates = (
        Objective.objects.filter(active=True)
        .values('user', 'objective_type', 'title')
        .annotate(cnt=Count('id'))
        .filter(cnt__gt=1)
    )

    for dup in duplicates:
        objs = (
            Objective.objects.filter(
                user=dup['user'],
                objective_type=dup['objective_type'],
                title=dup['title'],
                active=True,
            )
            .order_by('created_at', 'id')
            .iterator()
        )
        keep_first = True
        for obj in objs:
            if keep_first:
                keep_first = False
                continue
            obj.active = False
            obj.save(update_fields=['active'])


class Migration(migrations.Migration):

    dependencies = [
        ('goal_calendars', '0004_add_goalcalendar_timestamps'),
        ('objectives', '0002_add_objective_timestamps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(deactivate_duplicate_objectives, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='objective',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('user', 'objective_type', 'title'), name='unique_active_objective_user_type_title'),
        ),
    ]
