@rootUrl = http://localhost:8000
@baseUrl = {{rootUrl}}/api/v1

@access = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyMjkzMDc5LCJpYXQiOjE3NzIyOTIxNzksImp0aSI6ImNlMThmNmYwY2U0YzQxM2Q4ZDRiYmNmN2Y1MjYwOGM1IiwidXNlcl9pZCI6IjI5NmI2YzBiLTAwMTctNDFkNi04MWNjLWVjOWQ5YjZiYjhjMiJ9.76TCDHKP8y_DPQbD3dAQetokNvxDoLFiFc4gK4mcWl0
@walletId = 98b8b431-285b-41ff-bf5a-d4fbb3c0be90
@expenseCycleId = 2c5e5d9c-54f1-424b-be07-776f7cee6e6a


### Resolve cycle by date (create if missing)
POST {{baseUrl}}/wallets/cycle/resolve/
Authorization: Bearer {{access}}
Content-Type: application/json

{
  "wallet": "{{walletId}}",
  "date": "2026-03-10"
}

### Resolve cycle by month (create if missing)
POST {{baseUrl}}/wallets/cycle/resolve/
Authorization: Bearer {{access}}
Content-Type: application/json

{
  "wallet": "{{walletId}}",
  "month": "2026-03"
}

### List expense cycles by wallet (query param required)
GET {{baseUrl}}/wallets/cycle/?wallet={{walletId}}
Authorization: Bearer {{access}}

### Expense cycle detail
GET {{baseUrl}}/wallets/cycle/{{expenseCycleId}}/
Authorization: Bearer {{access}}

### Expense cycle billing summary
GET {{baseUrl}}/wallets/cycle/{{expenseCycleId}}/billing-summary/
Authorization: Bearer {{access}}

### Update expense cycle limit (PUT)
PUT {{baseUrl}}/wallets/cycle/{{expenseCycleId}}/
Authorization: Bearer {{access}}
Content-Type: application/json

{
  "limit": "1800.00"
}

### Update expense cycle limit (PATCH)
PATCH {{baseUrl}}/wallets/cycle/{{expenseCycleId}}/
Authorization: Bearer {{access}}
Content-Type: application/json

{
  "limit": "1500.00"
}
