# Generated by Django 5.2.8 on 2026-02-26 00:00

import uuid
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cycle_limit_default', models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    'cycle_starts',
                    models.PositiveSmallIntegerField(
                        validators=[
                            MinValueValidator(1, message='Cycle start day must be between 1 and 31.'),
                            MaxValueValidator(31, message='Cycle start day must be between 1 and 31.'),
                        ]
                    ),
                ),
                (
                    'cycle_ends',
                    models.PositiveSmallIntegerField(
                        validators=[
                            MinValueValidator(1, message='Cycle end day must be between 1 and 31.'),
                            MaxValueValidator(31, message='Cycle end day must be between 1 and 31.'),
                        ]
                    ),
                ),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name='wallets',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [
                    models.UniqueConstraint(
                        condition=models.Q(('active', True)),
                        fields=('user', 'name'),
                        name='unique_active_wallet_user_name',
                    ),
                    models.CheckConstraint(check=models.Q(('limit__gt', 0)), name='wallet_limit_gt_zero'),
                    models.CheckConstraint(
                        check=models.Q(('cycle_limit_default__gt', 0)),
                        name='wallet_cycle_limit_default_gt_zero',
                    ),
                    models.CheckConstraint(
                        check=models.Q(('limit__gte', models.F('cycle_limit_default'))),
                        name='wallet_limit_gte_cycle_limit_default',
                    ),
                    models.CheckConstraint(
                        check=~models.Q(('cycle_starts', models.F('cycle_ends'))),
                        name='wallet_cycle_starts_ne_cycle_ends',
                    ),
                ],
            },
        ),
    ]
