# Generated by Django 5.2.8 on 2026-02-26 00:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wallets', '0002_expensecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField(help_text='First day of the cycle month (YYYY-MM-01).')),
                ('limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'wallet',
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name='expense_cycles',
                        to='wallets.wallet',
                    ),
                ),
            ],
            options={
                'ordering': ['-month', '-created_at'],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('wallet', 'month'),
                        name='unique_expense_cycle_wallet_month',
                    ),
                    models.CheckConstraint(
                        check=models.Q(('limit__gt', 0)),
                        name='expense_cycle_limit_gt_zero',
                    ),
                ],
            },
        ),
    ]
