# Generated by Django 4.2.16 on 2026-02-27 02:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_expensecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentSerie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=120)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('installments_count', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installment_series', to='wallets.expensecategory')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_series', to='wallets.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recurring_canceled_from', models.DateField(blank=True, help_text='First day (YYYY-MM-01) from which recurring should not generate entries.', null=True)),
                ('description', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('single_expense', 'Single expense'), ('recurring_expense', 'Recurring expense'), ('installment_expense', 'Installment expense')], max_length=32)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='wallets.expensecategory')),
                ('expense_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='wallets.expensecycle')),
                ('installment_serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='wallets.installmentserie')),
                ('recurring_root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_occurrences', to='wallets.expense')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='installmentserie',
            constraint=models.CheckConstraint(check=models.Q(('total_amount__gt', 0)), name='installment_serie_total_amount_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='installmentserie',
            constraint=models.CheckConstraint(check=models.Q(('installments_count__gte', 1)), name='installment_serie_installments_count_gte_one'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='expense_amount_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('installment_serie__isnull', False), ('type', 'installment_expense')), models.Q(('type', 'installment_expense'), _negated=True), _connector='OR'), name='expense_installment_requires_installment_serie'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(check=models.Q(('type', 'installment_expense'), ('installment_serie__isnull', True), _connector='OR'), name='expense_non_installment_without_installment_serie'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(check=models.Q(('recurring_root__isnull', True), ('type', 'recurring_expense'), _connector='OR'), name='expense_recurring_root_only_for_recurring_type'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('recurring_canceled_from__isnull', True), ('recurring_root__isnull', True)), models.Q(('recurring_canceled_from__isnull', False), ('recurring_root__isnull', True)), models.Q(('recurring_canceled_from__isnull', True), ('recurring_root__isnull', False)), _connector='OR'), name='expense_recurring_canceled_only_on_roots'),
        ),
    ]
