# Generated by Django 4.2.16 on 2026-02-28 02:24

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_installmentserie_expense_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='expensecategory',
            name='unique_expense_category_user_name',
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(models.F('user'), django.db.models.functions.text.Lower('name'), name='unique_expense_category_user_name_ci'),
        ),
    ]
