# Generated by Django 5.2.8 on 2025-11-17 01:28

import django.db.models.deletion
import yearly_goal_slice.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalCalendar',
            fields=[
                ('id', yearly_goal_slice.fields.UUIDAutoField(auto_created=True, serialize=False, verbose_name='ID')),
                ('num_weeks', models.PositiveIntegerField(default=12)),
                ('start_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
