# Generated by Django 5.2.8 on 2025-11-17 01:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_calendars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalcalendar',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
