# Generated by Django 5.2.8 on 2025-11-17 02:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_calendars', '0002_alter_goalcalendar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalcalendar',
            name='title',
            field=models.CharField(default='Goal calendar', max_length=255),
        ),
        migrations.AlterField(
            model_name='goalcalendar',
            name='num_weeks',
            field=models.PositiveIntegerField(default=12, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(53)]),
        ),
    ]
