# Generated by Django 5.2.8 on 2025-11-22 02:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_calendars', '0003_goalcalendar_title_alter_goalcalendar_num_weeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalcalendar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goalcalendar',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
