# Generated by Django 5.2.8 on 2025-11-27 00:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_calendars', '0004_add_goalcalendar_timestamps'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('week_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('metric_type', models.CharField(choices=[('FREQUENCY', 'Frequency'), ('QUANTITY', 'Quantity'), ('SPECIFIC_DAYS', 'Specific days')], max_length=20)),
                ('target_frequency', models.PositiveIntegerField(blank=True, null=True)),
                ('target_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('specific_days', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal_calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_activities', to='goal_calendars.goalcalendar')),
            ],
            options={
                'ordering': ['week_number', 'title'],
            },
        ),
    ]
