# Generated by Django 5.2.8 on 2025-11-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_calendars', '0005_weeklyactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyactivity',
            name='completed_days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='weeklyactivity',
            name='frequency_progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weeklyactivity',
            name='quantity_progress',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
