# Generated by Django 4.2.16 on 2026-02-04 19:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('goal_calendars', '0006_weeklyactivity_completed_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalCalendarWeek',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_num', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('start_week', models.DateField()),
                ('end_week', models.DateField()),
                ('report', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal_calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='goal_calendars.goalcalendar')),
            ],
            options={
                'ordering': ['week_num'],
            },
        ),
        migrations.AddConstraint(
            model_name='goalcalendarweek',
            constraint=models.UniqueConstraint(fields=('goal_calendar', 'week_num'), name='unique_goal_calendar_week_num'),
        ),
    ]
