# Generated by Django 4.2.16 on 2026-02-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_calendars', '0007_goalcalendarweek_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalcalendarweek',
            name='end_week',
        ),
        migrations.AlterField(
            model_name='goalcalendarweek',
            name='report',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
