# Generated by Django 4.2.16 on 2026-02-04 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goal_calendars', '0008_remove_goalcalendarweek_end_week_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalcalendarweek',
            name='start_week',
        ),
    ]
