# Generated by Django 4.2.16 on 2026-02-04 19:41

from django.db import migrations, models
import django.db.models.deletion


def forward_populate_week(apps, schema_editor):
    GoalCalendar = apps.get_model('goal_calendars', 'GoalCalendar')
    GoalCalendarWeek = apps.get_model('goal_calendars', 'GoalCalendarWeek')
    WeeklyActivity = apps.get_model('goal_calendars', 'WeeklyActivity')

    for calendar in GoalCalendar.objects.all():
        existing = set(
            GoalCalendarWeek.objects.filter(goal_calendar_id=calendar.id).values_list('week_num', flat=True)
        )
        for week_num in range(1, calendar.num_weeks + 1):
            if week_num not in existing:
                GoalCalendarWeek.objects.create(
                    goal_calendar_id=calendar.id,
                    week_num=week_num,
                    active=True,
                )

    for activity in WeeklyActivity.objects.all():
        if activity.week_id:
            continue
        week = GoalCalendarWeek.objects.filter(
            goal_calendar_id=activity.goal_calendar_id,
            week_num=activity.week_number,
        ).first()
        if not week:
            week = GoalCalendarWeek.objects.create(
                goal_calendar_id=activity.goal_calendar_id,
                week_num=activity.week_number,
                active=True,
            )
        activity.week_id = week.id
        activity.save(update_fields=['week'])


def backward_unset_week(apps, schema_editor):
    WeeklyActivity = apps.get_model('goal_calendars', 'WeeklyActivity')
    WeeklyActivity.objects.update(week=None)


class Migration(migrations.Migration):

    dependencies = [
        ('goal_calendars', '0009_remove_goalcalendarweek_start_week'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklyactivity',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='weeklyactivity',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_activities', to='goal_calendars.goalcalendarweek'),
        ),
        migrations.RunPython(forward_populate_week, backward_unset_week),
        migrations.RemoveField(
            model_name='weeklyactivity',
            name='goal_calendar',
        ),
        migrations.RemoveField(
            model_name='weeklyactivity',
            name='week_number',
        ),
    ]
