# Generated by Django 4.2.16 on 2026-02-04 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goal_calendars', '0010_alter_weeklyactivity_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyactivity',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_activities', to='goal_calendars.goalcalendarweek'),
        ),
    ]
