# Generated by Django 4.2.16 on 2026-02-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_calendars', '0011_alter_weeklyactivity_week_non_nullable'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='weeklyactivity',
            constraint=models.UniqueConstraint(fields=('week', 'title'), name='unique_week_activity_title'),
        ),
    ]
